pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        IMAGE_TAG = "${env.BUILD_NUMBER}"

        AWS_ACCESS_KEY_ID     = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
    }

    stages {

        stage('Setup Tools') {
            steps {
                sh '''
                    mkdir -p /tmp/tools
                    cd /tmp/tools

                    # Install Docker client
                    if [ ! -f /tmp/docker/docker ]; then
                        curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-24.0.7.tgz -o docker.tgz
                        tar -xzf docker.tgz
                        chmod +x docker/docker
                    fi

                    # Install AWS CLI
                    if [ ! -f /tmp/bin/aws ]; then
                        curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
                        unzip -q awscliv2.zip
                        ./aws/install --install-dir /tmp/aws-cli --bin-dir /tmp/bin
                    fi

                    /tmp/docker/docker version
                    /tmp/bin/aws --version
                '''
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Get AWS Account ID') {
            steps {
                script {
                    env.ACCOUNT_ID = sh(
                        script: "/tmp/bin/aws sts get-caller-identity --query Account --output text",
                        returnStdout: true
                    ).trim()

                    env.ECR_BASE = "${env.ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com"

                    echo "ECR = ${env.ECR_BASE}"
                }
            }
        }

        stage('Docker Login') {
            steps {
                sh """
                    /tmp/bin/aws ecr get-login-password --region ${AWS_REGION} | \
                    /tmp/docker/docker login --username AWS --password-stdin ${ECR_BASE}
                """
            }
        }

        stage('Build Image') {
            steps {
                sh """
                    /tmp/docker/docker build -t stockai:${IMAGE_TAG} .
                """
            }
        }

        stage('Tag Image') {
            steps {
                sh """
                    /tmp/docker/docker tag stockai:${IMAGE_TAG} ${ECR_BASE}/stockai:${IMAGE_TAG}
                """
            }
        }

        stage('Push Image') {
            steps {
                sh """
                    /tmp/docker/docker push ${ECR_BASE}/stockai:${IMAGE_TAG}
                """
            }
        }
    }

    post {
        success {
            echo "SUCCESS"
        }

        failure {
            echo "FAILED"
        }
    }
}